### ISSUE TITLE
GET /page/{pageid} route and test

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-services#19]
Part of #8 

The application needs to register an endpoint pattern for `/page` which handles the GET method.   Code in the support for a pattern like `/project/{id}`.  For example:

```
GET
http://localhost:3001/page/123
```

The asynchronous endpoint will do various bits of logic (TBD at a later time) and respond with a JSON Object (which will be a 'page' from a TPEN Project Entity).  The endpoint response will need CORS headers as described by #9.  This endpoint does not require authentication and so will not include an Authorization header to process nor any user validation.

REST responses
- `200 Success` if there exists a page with the give id.  The page object JSON is put into the response body.
- `400 Bad Request` if there is no project ID
- `400 Bad Request` if the project ID is not a number
- `404 Not Found` if no project with the given ID exists
- `500` for other internal errors

Use test driven development to make an endpoint which does just this (at a minimum).  Write unit tests which test just your endpoint specifically and pass/fail as expected.  These tests will be written with jest.  Separate out which type of test it is by specifying a "#name" in the describe() declaration.  You MUST specify a name or your tests will be skipped. There are 3 names to use right now.

- #exists_unit
- #functions_unit
- #end2end_unit

Run your unit tests like

```
npm run unitTests
```

Tests should include
- Is the route registered with the app
- Does the route process the existence and lack of the {id} section of the request
- Does the route return the correct RESTful error code
- Does the route return the expected object type
- Does it succeed an end-to-end request
> Note:  None of these tests should need to spin up the entire app.

**Comment by thezeeshanhassan** [comment]
Hello, I am excited to share you that I am able to do your task. Can You assign it to me?
Best Wishes,

**Comment by cubap** [comment]
> Hello, I am excited to share you that I am able to do your task. Can You assign it to me? Best Wishes,

Good luck, @thezeeshanhassan , we'll review any PR you submit.

**Comment by thehabes** [comment]
hmm...let's make sure one of our OSS team members picks this one up.  @thezeeshanhassan is not real.
