### ISSUE TITLE
GET /project/{projid} route and test

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-services#2]
Part of #8 

The application needs to register an endpoint pattern for `/project` which handles the GET method.   Code in the support for a pattern like `/project/{id}`.  For example:

```
GET
http://localhost:3001/project/123
```

The asynchronous endpoint will do various bits of logic (TBD at a later time) and should respond with a JSON Object (which will be a TPEN Project Entity).  The endpoint response will need CORS headers as described by #9.  This endpoint does not require authentication and so will not include an Authorization header to process nor any user validation.

REST responses
- `200 Success` if there exists a project with the give id.  The Project object JSON is put into the respons body.
- `400 Bad Request` if there is no project ID
- `400 Bad Request` if the project ID is not a number
- `404 Not Found` if no project with the given ID exists
- `405 Wrong Method` if any other method besides 'GET' is used
- `500` for other internal errors

Use test driven development to make an endpoint which does just this (at a minimum).  Write unit tests which test just your endpoint specifically and passes/fails as expected.  These tests will be written with jest.  Separate out which type of test it is by specifying a "#name" in the describe() declaration.  You MUST specify a name or your tests will be skipped. There are 3 names to use right now.

- #exists_unit
- #functions_unit
- #end2end_unit

Run your unit tests like

```
npm run unitTests
```

Tests should include
- Is the route registered with the app
- Does the route process the existence and lack of the {id} section of the request
- Does the route return the correct RESTful error code
- Does the route return the expected object type
- Does it succeed an end-to-end request

> Note:  None of these tests should need to spin up the entire app.

**Comment by thehabes** [comment]
It is worth noting that we are not sure where project information lives.  It could be in the TPEN static repository, it could be in its own MariaDB, it could be in RERUM or a sister instance of RERUM.

**Comment by cubap** [comment]
![image](https://github.com/CenterForDigitalHumanities/TPEN-services/assets/1119165/21722c29-2782-4d3c-ab61-67fec383f8c4)

I think this could be discussed. I think much of the config and permissions stuff does not need to be public, but maybe a version of Project with links to readonly pages, license information, or other stuff is useful to have.

One reasonable solution would be to consider it like overloaded Java Classes. Project(id) would send a public JSON-LD object but Project(id, auth) would further supplement with all the needed metadata for Interfaces to organize. This would be easy for a developer to detect and we could still throw Errors if the `auth` is included but not valid. In fact, this could stratify further for collaborators who have access to only some Project settings.
