### ISSUE TITLE
Connect to MongoDB

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-services#59]
We are spoiled for options as we have multiple remote MongoDBs.  

- Atlas Production
- Atlas Development
- Mongo on img01

Create a database connector knowing that the connection string will vary.  Connect to the mongo on img01 as a start, and we can upgrade to Atlas Development when we are at a later stage.

**Comment by cubap** [comment]
Picking this up for the "Mongo on IMG" version database controller abstraction

**Comment by thehabes** [comment]
Things have shifted and the scope of this has been split.  This is now a duplicate of #76
