### ISSUE TITLE
Content Negotation

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-services#61]
For description see 
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation
- https://iiif.io/api/presentation/3.0/#63-responses

On a property-by-property basis you will need to negotiate between the following.

- https://iiif.io/api/presentation/2.1/
- https://iiif.io/api/presentation/3.0/

**Comment by cubap** [comment]
https://iiif-commons.github.io/manifesto/
https://github.com/IIIF-Commons/manifold
