### ISSUE TITLE
Initiate User Entity Class

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-services#88]
A module for a "User" is needed for use by the other services. In TPEN, a User is a container for a `userPreferences` object with an _id. The module should support the methods needed to GET or CRUD user preferences.  Other TPEN Services may import and use this module for interaction with `userPreferences` as needed.  Some `userPreferences` information can be public while other information can be strictly private.  A TPEN3 `userPreferences` object will always know its associated RERUM Agent, which is used for data attribution.  

> Note:  We need to produce and connect this issue with the appropriate TPEN3 User documentation/documents which describe a userPreference

Current related issues are #69, #70, #71

**Comment by cubap** [comment]
`userPreferences` is now `users`

**Comment by jsvoo** [comment]
@cubap technically, POSTing to user object will be adding to the object or expected to. Should that be PUT? I'm thinking of a clear situation where we actually need to POST since the user class does not include any writing methods besides updateRecord
